// dependencies
import "../css/globals.css";
import localFont from "next/font/local";
import ProviderQuery from "./ProviderQuery";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

// fonts
const vazir_regular = localFont({
    src: "../../public/fonts/Vazir.woff2",
});
const vazir_medium = localFont({
    src: "../../public/fonts/Vazir-Medium.woff2",
    variable: "--font-vazir-medium",
});

// head
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// html & body
export default function RootLayout({ children }) {
    return (
        <html lang="en" dir="rtl">
            <body
                className={`${vazir_regular.className} ${vazir_medium.variable}`}
            >
                <ProviderQuery>
                    {children}
                    <ReactQueryDevtools />
                </ProviderQuery>
            </body>
        </html>
    );
}
